services:
  - type: web
    name: blogs-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true
    branch: main
    rootDir: .
